apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-project
  labels:
    app: flask-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-project
  template:
    metadata:
      labels:
        app: flask-project
    spec:
      containers:
      - name: flask-project
        image: seyma1km/flask-project:latest
        ports:
        - containerPort: 5000
